# You can use this to run the e2e tests in a docker container running in frontend below
# To run:
# docker-compose -f docker-compose-e2e-tests.yml build
# docker-compose -f docker-compose-e2e-tests.yml up

version: '3'
services:
  db:
    image: postgres:11.12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flagsmith
    container_name: flagsmith_postgres

  flagsmith-api:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      E2E_TEST_AUTH_TOKEN: some-token
      FE_E2E_TEST_USER_EMAIL: nightwatch@solidstategroup.com
      DJANGO_ALLOWED_HOSTS: '*'
      DATABASE_URL: postgresql://postgres:password@db:5432/flagsmith
      DISABLE_ANALYTICS_FEATURES: 'true'
      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db

  frontend:
    build:
      context: ../
      dockerfile: frontend/Dockerfile.e2e
    platform: linux/amd64
    environment:
      E2E_TEST_TOKEN_DEV: some-token
      DISABLE_ANALYTICS_FEATURES: 'true'
      FLAGSMITH_API: flagsmith-api:8000/api/v1/
      SLACK_TOKEN: ${SLACK_TOKEN}
    ports:
      - 8080:8080
    depends_on:
      - flagsmith-api
    links:
      - flagsmith-api:flagsmith-api
    command: [npm, run, test]
