name: Frontend Publish Docker Images

on:
  push:
    tags:
      - '*'
    paths:
      - frontend/**
      - .github/**

jobs:
  build-frontend-dockerhub:
    runs-on: ubuntu-latest
    name: Frontend Publish Docker Image

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            flagsmith/flagsmith-frontend
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Write git info to Docker image
        run: |
          cd frontend
          echo ${{ github.sha }} > CI_COMMIT_SHA

      - name: Download features
        run: >
          curl --location --request GET 'https://api.flagsmith.com/api/v1/flags/' --header 'X-Environment-Key: ${{
          secrets.FLAGSMITH_ENVIRONMENT_KEY }}' > frontend/flags.json

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          file: frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
