name: Frontend E2E Publish Docker Images

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - frontend/**
      - .github/**

jobs:
  build-frontend-e2e-dockerhub:
    runs-on: ubuntu-latest
    name: Frontend E2E Publish Docker Image

    steps:
      - name: Cloning repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            flagsmith/flagsmith-e2e-tests
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/heads/main') }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push E2E testing docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: frontend/Dockerfile.e2e
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            CHROME_URL=${{ secrets.CHROME_URL }}
