name: Publish Flagsmith Private Cloud Image

on:
  push:
    tags:
      - '*'

env:
  FLAGSMITH_SAML_REVISION: v1.1.0
  FLAGSMITH_RBAC_REVISION: v0.3.1
  FLAGSMITH_WORKFLOWS_REVISION: v1.2.5
  FLAGSMITH_AUTH_CONTROLLER_REVISION: v0.0.1

jobs:
  build-dockerhub:
    runs-on: ubuntu-latest
    name: Platform Publish Docker Image

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3

      - name: Checkout SAML package
        uses: actions/checkout@v3
        with:
          repository: flagsmith/flagsmith-saml
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.flagsmith_saml_revision }}
          path: ./flagsmith-saml

      - name: Integrate SAML module
        run: |
          mv ./flagsmith-saml/saml ./api

      - name: Checkout Workflows Logic package
        uses: actions/checkout@v3
        with:
          repository: flagsmith/flagsmith-workflows
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.flagsmith_saml_revision }}
          path: ./flagsmith-workflows

      - name: Integrate Workflows Logic module
        run: mv ./flagsmith-workflows/workflows_logic ./api/features/workflows/logic

      - name: Checkout Auth Controller package
        uses: actions/checkout@v3
        with:
          repository: flagsmith/flagsmith-auth-controller
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.FLAGSMITH_AUTH_CONTROLLER_REVISION }}
          path: ./flagsmith-auth-controller

      - name: Integrate Auth Controller module
        run: mv ./flagsmith-auth-controller/auth_controller ./api
        shell: bash

      - name: Checkout RBAC module
        uses: actions/checkout@v3
        with:
          repository: flagsmith/flagsmith-rbac
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.flagsmith_rbac_revision }}
          path: ./flagsmith-rbac

      - name: Integrate RBAC module
        run: mv ./flagsmith-rbac/rbac ./api
        shell: bash

      - name: Write git info to Docker image
        run: |
          cd api
          echo ${{ github.sha }} > CI_COMMIT_SHA
          echo '' > ENTERPRISE_VERSION

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            flagsmith/flagsmith-private-cloud
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          build-args: |
            SAML_INSTALLED=1
            POETRY_OPTS=--with saml,auth-controller
